apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack 
  namespace: argocd          
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sagarbaratam/observability-stack.git 
    targetRevision: HEAD 
    path: charts/kube-prometheus-stack 
    helm:
      valueFiles:
        - my-custom-values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
