apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-allinone
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: obs-monitoring
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 0.71.13
    helm:
      values: |
        allInOne:
          enabled: true
          image:
            tag: "1.53"
          service:
            type: NodePort
            nodePort: 30006
        collector:
          enabled: false
        agent:
          enabled: false
        query:
          enabled: false
        storage:
          type: memory
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
