apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: test-tls-secret
  namespace: test-app
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREE1TVJJd0VBWURWUVFEREFsc2IyTmgKYkdodmMzUXhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWURWUVFIREExVFlXNGdSbkpoYm1OcGMyTnZNQjRYRFRJMQpNRFl4T0RBMk5UUXlObG9YRFRJMk1EWXhPREEyTlRReU5sb3dPVEVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wCk1Rc3dDUVlEVlFRR0V3SlZVekVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6Q0NBU0l3RFFZSktvWkkKaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMTUpwczA5Q0UvZ3R6TlUvQXlrZTc2aUFjdzBMZG5Ha2NpVApIazl3eXlTSmc4NlRpY1hISys0QmQyc1BKRnVHaEhjUWZzNm5oQkRiUmJKSEt3dGY3YkZpZ3c0ckMwY2NFY0RECnFQQ1VvdlFUenBFbnNaOHNEa0pKS09tZEYxcVFNYU05aVB3b0VleEd6ajI5a1plZ1ZDMm1CY0ZQNXZIM3Vma0QKZDBZY1Z6enQ5VnQ5b0xYVXk3cHFXZWNnTHJpNmp5K1ZxUk1BQW5tTkpLVmJ4L2xKL3NsZVhUSVR6aUVTNmtuUgpSaW03TCszaFMzQTRXUGllWW9HVFp2RzNFQnBzdFIwNmlNVG5BMlc3V0NhczZRQWcyUlQ4MHE4cWkxRVdrMXBRCkR4KzdqMWNBTElNSks3a2V3K1F4SlFDZTg5VnFrVUIxWEVhdVR4dkwrQ2pyV1ZCMVh0OENBd0VBQWFOQ01FQXcKSFFZRFZSME9CQllFRk5leEs2RFNLZDUzcUhhSHh6ZVE4RzY5ZDNUV01COEdBMVVkSXdRWU1CYUFGS2pxZVl2cQpkWXBNbFJBWWRhTTBYdS9iMFF3WE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlhXVVl1RFptV2hpemtoK0RSCmdvWklUMzlyTWhLT2NtNXBjeUNDMUJLb29jSE42eGtHcSs4UUxLcmdyZmxaenZXKzdVWjB0Ny9kaHZ3UGhURXUKb25IRVZjWU14VjRoQVBiOWlQVEJ4QmdSclFpR2FESlU5NXFOc3VyUU5VOTRqaXE3aDJscXpKdXVCTlpDWlp6Mgo5WXBOZEN2aStZSVVUQ1NoYjJhOERneXNxamFLRXBYUTdtdlJOTVZrMnhWWHJSanJML0l4Nk1ZOEMwWUgrZzNxCmxDSXVYU0hXb1Q3czFQWVhRRVUzOFYrVU5jc05jTVBrazl2TlNoakxWdjI0SGxKWHZqQkYxTWtVUS9iNjBmcFIKS2pvUXIwbUVZVEk5YTJNc05qby9TaFBxald5Q1R3S0phUGN3dTB0YmdJYXBxNCtqYjlmOG80WVBqSXhoZDFSbQp0VCsrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3pDYWJOUFFoUDRMY3oKVlB3TXBIdStvZ0hNTkMzWnhwSElreDVQY01za2lZUE9rNG5GeHl2dUFYZHJEeVJiaG9SM0VIN09wNFFRMjBXeQpSeXNMWCsyeFlvTU9Ld3RISEJIQXc2andsS0wwRTg2Uko3R2ZMQTVDU1NqcG5SZGFrREdqUFlqOEtCSHNSczQ5CnZaR1hvRlF0cGdYQlQrYng5N241QTNkR0hGYzg3ZlZiZmFDMTFNdTZhbG5uSUM2NHVvOHZsYWtUQUFKNWpTU2wKVzhmNVNmN0pYbDB5RTg0aEV1cEowVVlwdXkvdDRVdHdPRmo0bm1LQmsyYnh0eEFhYkxVZE9vakU1d05sdTFnbQpyT2tBSU5rVS9OS3ZLb3RSRnBOYVVBOGZ1NDlYQUN5RENTdTVIc1BrTVNVQW52UFZhcEZBZFZ4R3JrOGJ5L2dvCjYxbFFkVjdmQWdNQkFBRUNnZ0VBRTRGSDEvdEFDNzBUdmJhOVZqNllocU80RU1CWE1HOFJmeW14VEg2aGV3TzAKOERmNFNLdVN1SFZyY1B2dmZqM1E4a3hzbHVTcGRDYXNyZjFTamdUYVFlV0FHVXZpTTN5TGlKWFRDQkZzRVZnKwpaeEpOSjd0UkpiS1B1bEpxeUJYYno5NGYyRGQyQUdqcHNOQ1ZheVh2UUhhTkVQV1NBbEYybVhvM0JTbmRsOTIyCmVJVVAya1FsRHZ2RnhVQUJrb0pkSXZkSUM3YWlHSi80RTI0cGM1SE1JYkdpWmRUMFNmRlhJKzQ4Q3JRaEExY24KeVZrZjg2S0JRZGpjaHZZY2ZiaVdyM2FxS3Q3MkJzOHc4SmRmVXJ0eGVvMW1CRmJFTi9INlVFVVgwUmRad3RoKwpUNXNpWlNOZnhnb2JyQUFNQ1U4SzJCY0hPdGh1VFpnYXhKemNEeFhpYVFLQmdRRHhaQ2ZDaDFIa2Q4ZHFVRDFWCkxESm12KzIxSmpHK3NSRVdYeUNnS1VPYTkrYkRCNTdaMXZ1Yi8vUVp4a0didy9COEpXMUJDNEJLMmdFWWdFSTEKaVhtdGRUVE1aWXhYMFlZNkpKUnVVSGdUeXdZN2hia2pkVDdUdWtiM2NxaW9ZMlBUUWpDaWlNYy9TbURTT0tOaAoxU2pHU1EwajIrbENPYi8vN3F0UFBZYWxHUUtCZ1FDOTMzWHUxN00zOFJvVVc2cllLd0NKVjBQNTZidlMrVGNsCm1JUWpFa2hLWGdveTVHYXhCMTh5elVKK3daQ1NkTEZTMXJXYS8xdUJGZ2YxTHA0UXBkYU5ZMmd0Y01Uck5Nbi8KTmQyRE1ySEV5d2RDdWZQK2dqYzR1cVMyZWwvay9ZNnh0RmZqTVlpS2lEQndBdDk1K2l1Mlo1dkgxaG80RHNYLwpTZ2lucGNGcXR3S0JnUUNlMlZETTAyM1JrZno1ZWhvU1RZWlJWV1hnK21ScjMydW1OQzF0R0JwMEJVU20vUUhNCnlvdEN5amxoS0xVT0F1L2pVbUhHRndKeXYybFBMVC9rcVRZWUxuUHpPYlFVS2o1UlRyY2FyUHVIMHVla0RjaWEKaTlJdlZIclU1WEFWZDJvK29HVU80RUYxNWNVM01heGFlZ0plRWI2QzVYbG5ha2R0N1Nwd2Q4VitLUUtCZ1FDcwo2eWEzUnlBRHNZTGp5WHYwOUd5L3A0YlR3Z2I1STFnUzJDeDIyRDZYNDc3OERFQnR0dDMvSVNvTzBHKyt3YUdBClpPUHRiZVBDMHZLYVcwTSt2Qm1DbUdhWEE1MkM2NGVPOGxwekVxY05KeTNNbWhkWTBQUkRxTTg3RklYaXdQekUKWUE2dWJUMEJsUGd2K3AzVnMzMDkyR3ZwK2RYVStiZGVRT2xTN01VU1R3S0JnRW1BY0gzblQ2VXlQUy9kUmJzSgpKTEE2QXYzWDlpejl0RnpCdXRCbkVOTlN2TlFDYjZFa1lCTVd1bG4yMnA0STBIVndPMGdwNHl4c3NlTnJYS3lGCklqQTBsakxUWmpZUzZzVHc4clEvc3l4ZHlpUFI3NkoyNDJNVEF6eEljbzNnZzF2VW1VUU40R3RDanlKSThCRDkKWWtrWnNWS0k4TC9kVWhDN09uVWNJSlBXCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1h
  values:
    controller:
      hostNetwork: true
      kind: DaemonSet
      service:
        type: NodePort
        nodePorts:
          http: 30000
          https: 30001
      admissionWebhooks:
        enabled: false
      extraArgs:
        default-ssl-certificate: "test-app/test-tls-secret"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - localhost
    secretName: test-tls-secret
  rules:
  - host: localhost
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80