# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: prometheus-community
#   namespace: monitoring
# spec:
#   interval: 1h
#   url: https://prometheus-community.github.io/helm-charts
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: kube-prometheus-stack
#   namespace: monitoring
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: kube-prometheus-stack
#       version: "48.1.1"
#       sourceRef:
#         kind: HelmRepository
#         name: prometheus-community
#         namespace: monitoring
#       interval: 1h
#   values:
#     prometheus:
#       prometheusSpec:
#         replicas: 1
#         securityContext:
#           runAsUser: 65534
#           runAsGroup: 65534
#           fsGroup: 65534
#           runAsNonRoot: true
#         storageSpec:
#           volumeClaimTemplate:
#             spec:
#               storageClassName: standard # Use Kind's default storage class
#               accessModes: ["ReadWriteOnce"]
#               resources:
#                 requests:
#                   storage: 10Gi
#       # --- ADDED/MODIFIED SECTION FOR PROMETHEUS SERVICE ---
#       service:
#         type: NodePort
#         nodePort: 30080 # This sets the NodePort to 30080
#         port: 9090      # This sets the ClusterIP service port
#         targetPort: 9090 # This sets the target port on the pod
#     # --- END ADDED/MODIFIED SECTION ---
#     grafana:
#       enabled: false # We'll deploy Grafana separately