apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "48.1.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1h
  values:
    prometheus:
      prometheusSpec:
        replicas: 2
        securityContext:
          fsGroup: 65534  # nobody
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: manual
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
              selector:
                matchLabels:
                  app: prometheus
    grafana:
      enabled: false  #Dummy comment
