apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.5.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h
  values:
    singleBinary:
      replicas: 2
      service:
        type: NodePort
        nodePort: 30004
      persistence:
        enabled: true
        storageClassName: standard
        size: 8Gi
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        runAsNonRoot: true

    # Agent operator enabled with logs mode
    agent:
      enabled: true
      mode: logs
      logs:
        instances:
          - name: default
            clients:
              - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
            positions:
              filename: /tmp/positions.yaml
            scrape_configs:
              - job_name: varlogs
                static_configs:
                  - targets: [localhost]
                    labels:
                      job: varlogs
                      host: ${HOSTNAME}
                      __path__: /var/log/*log

      extraVolumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true

      extraVolumes:
        - name: varlog
          hostPath:
            path: /var/log
